# Generated by Django 5.1.4 on 2024-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attached_graphs',
            field=models.ManyToManyField(related_name='attached_users', to='core.graph'),
        ),
    ]
