# Generated by Django 5.1.4 on 2024-12-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_attached_graphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attached_graphs',
            field=models.ManyToManyField(to='core.graph'),
        ),
    ]
