# Generated by Django 5.1.4 on 2024-12-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_node_graph_alter_user_attached_graphs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='graph',
            new_name='associated_graph',
        ),
    ]
