# Generated by Django 5.1.4 on 2024-12-18 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_node_delete_csvimporternode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('file', models.CharField(max_length=255)),
                ('file_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
