# Generated by Django 5.1.4 on 2024-12-18 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_csvimporter_delete_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimporter',
            name='output_port',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='csvimporter',
            name='file',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ColumnAdder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('output_port', models.CharField(default='', max_length=255)),
                ('expr', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Duplicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('output_ports', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('file', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filterer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('output_port', models.CharField(default='', max_length=255)),
                ('expr', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Joiner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_ports', models.CharField(default='', max_length=255)),
                ('output_port', models.CharField(default='', max_length=255)),
                ('join_column', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegexImporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('output_port', models.CharField(default='', max_length=255)),
                ('file', models.CharField(default='', max_length=255)),
                ('file_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('regex', models.CharField(default='', max_length=255)),
                ('columns', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('output_port', models.CharField(default='', max_length=255)),
                ('select_columns', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sorter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('output_port', models.CharField(default='', max_length=255)),
                ('sort_column', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Csv_Importer', 'Csv_Importer'), ('Column_Adder', 'Column_Adder'), ('Duplicator', 'Duplicator'), ('Exporter', 'Exporter'), ('Filterer', 'Filterer'), ('Joiner', 'Joiner'), ('Regex_Importer', 'Regex_Importer'), ('Selector', 'Selector'), ('Sorter', 'Sorter'), ('Viewer', 'Viewer')], max_length=100)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
