# Generated by Django 5.1.4 on 2024-12-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_csvimporter_output_port_alter_csvimporter_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnadder',
            name='type',
        ),
        migrations.RemoveField(
            model_name='csvimporter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='duplicator',
            name='type',
        ),
        migrations.RemoveField(
            model_name='exporter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='filterer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='joiner',
            name='type',
        ),
        migrations.RemoveField(
            model_name='regeximporter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='selector',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sorter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='type',
        ),
    ]
