# Generated by Django 5.1.4 on 2024-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_columnadder_input_data_columnadder_output_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duplicator',
            old_name='output_ports',
            new_name='output_port1',
        ),
        migrations.RenameField(
            model_name='joiner',
            old_name='input_ports',
            new_name='input_port1',
        ),
        migrations.AddField(
            model_name='duplicator',
            name='output_port2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='joiner',
            name='input_port2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
