# Generated by Django 5.1.4 on 2024-12-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_output_ports_duplicator_output_port1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='output_table',
            field=models.CharField(default='', max_length=255),
        ),
    ]
