# Generated by Django 5.1.4 on 2024-12-21 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_viewer_output_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='regeximporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
