# Generated by Django 5.1.4 on 2024-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_csvimporter_file_updated_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(default='1900-01-01T00:00:00'),
        ),
        migrations.AlterField(
            model_name='regeximporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(default='1900-01-01T00:00:00'),
        ),
    ]
