# Generated by Django 5.1.4 on 2024-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_regeximporter_file_updated_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='regeximporter',
            name='file_updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
