# Generated by Django 5.1.4 on 2025-01-15 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_csvimporter_file_updated_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('input_port', models.CharField(default='', max_length=255)),
                ('associated_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
